title: '#JustSayinPage'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 'Clever quotes, witty jokes and thoughts provoked...on the daily. '
color:
  saturation: 0.8
  brandStrength: 0.25
  lightness: 0.5276596
  brandColors:
    - '#000000'
    - '#ffffe7'
    - '#1e355e'
    - '#486d9a'
    - '#a7b5be'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: '@JustSayinPage'
    url: www.facebook.com/JustSayinPage
    type: external
name: JustSayinPage
favicon: null
analytics:
  twitter: null
  google: null
  facebook: '270880233073839'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.50335
layout_spectrum: 0.2595745
