name: JustSayinPage
favicon: null
layout_spectrum: 0.57776
typography_spectrum: 0.50335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffe7'
    - '#1e355e'
    - '#486d9a'
    - '#a7b5be'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
