title: '#JustSayinPage'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'Clever quotes, witty jokes and thoughts provoked...on the daily. '
color:
  saturation: 0.8
  brandStrength: 0.8808511
  lightness: 0.5276596
  brandColors:
    - '#FFFCE9'
    - '#000000'
    - '#02FAEC'
    - '#049DBF'
    - '#F87EE7'
  rhythmicContrast: 0.75
navigation:
  - name: '@JustSayinPage'
    url: www.facebook.com/JustSayinPage
    type: external
cta:
  bucket: null
  version: null
  domain: null
name: JustSayinPage
favicon: null
analytics:
  twitter: null
  google: null
  facebook: '270880233073839'
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.50335
layout_spectrum: 0.2595745
