typography_spectrum: 0.50335
color:
  brandColors:
    - '#000000'
    - '#ffffe7'
    - '#1e355e'
    - '#486d9a'
    - '#a7b5be'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.79873
analytics:
  google: null
  facebook: '270880233073839'
  twitter: null
name: JustSayinPage
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: '@JustSayinPage'
    url: www.facebook.com/JustSayinPage
    type: external
favicon: null
title: '#JustSayinPage'
description: 'Clever quotes, witty jokes and thoughts provoked...on the daily. '
purpose: []
